### ISSUE TITLE
Google Maps API Terms Violation

### ISSUE THREAD

**Issue by Xingyu96** [LiteFarmOrg/LiteFarm#1042]
Hi,

I was a student researcher involved with this project in 2018. Just today I was made aware that LiteFarm is still using the Google Maps API key I created back in 2018. I probably would have forgotten, except Google is threatening to restrict the API access in 7 days (June 14th) if the issue below is not addressed:

============

We are happy to see developers using the Google Maps Platform Service. However, we have detected that your application, {''litefarm.org'' }, does not fully comply with the [Google Maps Platform Terms of Service](https://cloud.google.com/maps-platform/terms/).

In particular, your application violates Section 3.2.2(b) of the terms, which requires developers to “display all attribution that (i) Google provides through the Services (including branding, logos, and copyright and trademark notices); or (ii) is specified in the [Maps Service Specific Terms](https://cloud.google.com/maps-platform/terms/maps-service-terms/).” In addition, developers are not allowed to “modify, obscure, or delete such attribution.”

Please update your application so that the [“Google logo missed on the map''] on the map displayed in your application is clearly visible as required by the terms of service.

We are bringing this to your attention so that this issue can be corrected and your application can be compliant with the Google Maps Platform Terms of Service. If this issue is not corrected, we will take action to restrict your access to the Google Maps API services.

Please reply to this email in the next 7 days to confirm you are updating your application to comply with the Google Maps Platform Terms of Service.

=============

So I think there's 2 actions current developers need to take immediately to remediate the issue:
1. Create a new Google Maps API key for LiteFarm and deprecate the current one which is still linked to my personal google account. (**I will be turning the API off on June 14th**)
2. Comply with Google's demand and display whatever logos they are asking for to continue using Google Maps API.

**Comment by kikemarquez8** [comment]
Hi! Thanks for bringing this to our attention, I'm working on this right now.

**Comment by kikemarquez8** [comment]
@Xingyu96 Issue has been resolved now, we have updated the API keys and added google logo and attributions. Thanks again for bringing this to our attention.
