### ISSUE TITLE
Deployment issue with Litefarm-api on localhost

### ISSUE THREAD

**Issue by raheelash** [LiteFarmOrg/LiteFarm#1321]
I followed the deployment guide as was mentioned in the "README.md" file using the docker in windows 10 environment, but i got issue on `docker-compose -f docker-compose.dev.yml up` command with Litefarm api , i am attaching the screenshot as well for further reference any help would be appreciated.
![Screenshot_2](https://user-images.githubusercontent.com/88946733/129458674-8fbf163a-fd81-45a3-a249-88e9412527c0.png)
![Screenshot_3](https://user-images.githubusercontent.com/88946733/129458679-dc655b56-7349-45e0-9dcc-b46e117b24ae.png)
also there is no ".env" file but a ".env.default" one inside the "api" directory which has to be modified a bit according to the "README.md" file, so i added the commands mentioned in the ".env.default" file. Any Help would be appreciated.

**Comment by kikemarquez8** [comment]
Hey Raheel, thanks for submitting the issue, we have updated our infrastructure since the last time we modified the docker file. I don't think we can provide a quick fix for this at the moment but we plan on getting into this on September!

**Comment by raheelash** [comment]
Hi kikemarquez8, I got it fixed the above mentioned issue but now I am getting new issue about the secrete key yet I have generated and added the JWT_SECRET in .env  file but I am getting this error in LiteFarm-api section.
![Screenshot_8](https://user-images.githubusercontent.com/88946733/129603429-9a3d51dd-1ea8-49c1-96bf-e6e913be0602.png)
