### ISSUE TITLE
Seeding issue, Some Tables not being created with migration.

### ISSUE THREAD

**Issue by raheelash** [LiteFarmOrg/LiteFarm#1393]
**Describe the bug**
'npm run migrate:dev:seed' --> this generate the error about the dependencies, ("put_all_dataset.js"), i have attached the screenshot, error is about these , 'fertilizerLog', 'fieldCrop', 'cropCommonName',
    'pestControlLog',  -- wen i performed the migration i explicitly check the tables of "mock_farm" db i have created in postgres, these tables were not created and all the tables carrying "Log" in there name aslo depends on the "activity_Log" as they get reference of the "activity_id", although the migration command should have created these tables, i have gone through the "knex" documentation and all, in short all the migrations were performed without any error, and yet the depencies table i mentioned above have the "create_tble" code through knex in respective files, but not created as they should have.
**To Reproduce**
1. create DB "mock_farm"
2. cd to this in terminal -->`cd packages/api` perform `npm run migrate:dev:db` then `npm run migrate:dev:seed`
3. the seeding will through error about dependencies

 

**Expected behavior**
The data should have seed into the tables of DB
**Screenshots**
![Screenshot_19](https://user-images.githubusercontent.com/88946733/131092644-03a0fdb4-4717-447b-b24c-3c3ad6bb277d.png)
![Screenshot_20](https://user-images.githubusercontent.com/88946733/131092662-3f25e3fc-0b8b-46a1-83d8-2849add2b3cc.png)

 

**Desktop (please complete the following information):**
 - OS: windows 10 Professional
 - Browser : Chrome
 - Version: 92.0.4515.159 (Official Build) (64-bit) 

 

**Smartphone (please complete the following information):**
 - Device: mi 9
 - OS: Android 11
 - Browser: Chrome

 

**Additional context**

**Comment by JimmyRowland** [comment]
Hi Raheel, thanks for raising the issues. Develop branch is still in progress, we won't be able to work on seeding issues until October.
