### ISSUE TITLE
Document upload error, Add New Expense types missing

### ISSUE THREAD

**Issue by raheelash** [LiteFarmOrg/LiteFarm#1414]
**Describe the bug**
When i try to upload the document i get {TypeError: Cannot read property 'valid_until' of undefined} error on the browserbut on the back-end i get {TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined"  for header "API-Key"} in the terminal, i have attached the screenshot as well, on debugging the code i get to know the value of API-KEY is comming from the .env file and in the documentation its not mentioned what is that key source, or how to generate that, Secondly in the Finances tab, in "add new Exxpense" i can't select any category of the expense because i think they come from the DB, and there is issue with seeding command, i have already uploaded the issue about that too. I am attaching the screenshot of it as well.

**To Reproduce**
1. Go to documents tab and click add new document select file and it will throw the error.
2. Go to the Finances tab and then add new expense it will load new page but there is no icon to select the category of the expense.

**Expected behavior**
should have gave the successful expected results.

**Screenshots**
![Screenshot_22](https://user-images.githubusercontent.com/88946733/131487473-0cd7d286-9985-4e54-b6f9-03df42994d98.png)
![Screenshot_23](https://user-images.githubusercontent.com/88946733/131487489-d515fc5d-d171-461c-b3c9-231b968aa374.png)
![Screenshot_24](https://user-images.githubusercontent.com/88946733/131487514-74cdfdd2-9bb8-408f-9a24-c86a6b06dce7.png)
 

**Desktop (please complete the following information):**
 - OS: windows 10 Professional
 - Browser : Chrome
 - Version: 92.0.4515.159 (Official Build) (64-bit) 

 

**Smartphone (please complete the following information):**
 - Device: mi 9
 - OS: Android 11
 - Browser: Chrome

 

**Additional context**

**Comment by JimmyRowland** [comment]
An S3 compatible storage is required to upload files
