### ISSUE TITLE
Task types not showing on the front-end from the Database Table

### ISSUE THREAD

**Issue by raheelash** [LiteFarmOrg/LiteFarm#1435]
**Describe the bug**
When i try to use a task in the task module which is already a default task, mostly does not appear on the frontend except the cleaning one, i have attached the screenshot as well. when i inspect the database table for task type it show the default task from id 1 to 5, i have attached the screenshot as well.
**To Reproduce**
1. Go to task tab and click "create a task".

**Expected behavior**
should have shown the task in the task menu.

**Screenshots**
![Screenshot_27](https://user-images.githubusercontent.com/88946733/132228919-94336b78-4f8a-4206-a461-bc8edb16ccd1.png)
![Screenshot_28](https://user-images.githubusercontent.com/88946733/132228937-6e05f934-72d6-4165-8619-6a1388f062ad.png)

 

**Desktop (please complete the following information):**
 - OS: windows 10 Professional
 - Browser : Chrome
 - Version: 92.0.4515.159 (Official Build) (64-bit) 

 

**Smartphone (please complete the following information):**
 - Device: mi 9
 - OS: Android 11
 - Browser: Chrome

 

**Additional context**

**Comment by JimmyRowland** [comment]
Here is a list of supported task types
![image](https://user-images.githubusercontent.com/16997894/143152819-987b3542-adc2-4425-80d7-f8a505325405.png)
