### ISSUE TITLE
Issue creating a new management plant

### ISSUE THREAD

**Issue by hernandcb** [LiteFarmOrg/LiteFarm#1689]
Hello guys, 

First of all, congratulations for the nice work on the project. I have been trying to run it but found an issue, I would like to confirm with you if this is a bug or perhaps there is a miss configuration on my side.

**Describe the bug**
There is an error trying to add a management plan. The API returns an status code 400 and the following error is shown in the API console: 
 TypeError: Cannot read property 'task_type_id' of undefined

**To Reproduce**
I tried both the docker containers and the local installation. 

1. To reproduce it using docker you should remove the previous volumes to ensure the DB is created from scratch:
$  docker-compose -f docker-compose.dev.yml down --volumes

2. Then run it again
$  make up

3. Create a new user, a farm and add a crop
4. Try to create a new management plan

**Expected behavior**
A management plan created.

**Screenshots**
In the image below you can see the error on the UI:
![UI_error_msg](https://user-images.githubusercontent.com/4978907/144276103-53585872-3bb0-4029-9202-e8b9975f26b6.png)

And the error on the request 
![request_error](https://user-images.githubusercontent.com/4978907/144275212-35b26acf-2885-4934-bce7-20ebfd945f78.png)

And this is the API message
![API_message](https://user-images.githubusercontent.com/4978907/144275211-6efbe9f8-12c1-435e-936f-98d4e84292c2.png)

**Additional context**

I went to the code and realize that there are some task types missing in the database. Among the missing ones are the Plant task and the Harvest task.  In the image below you can see the types of task present in the table:

![task_type_table](https://user-images.githubusercontent.com/4978907/144275207-99ae25f5-e462-41ba-9daa-0471ca96b093.png)

Thanks in advance!
Hernán

**Comment by JimmyRowland** [comment]
Can you switch to the `develop` branch, reset DB, add `NODE_ENV=development` to `packages/api/.env`, and run the migration again? It seems the following migration is skipped.
https://github.com/LiteFarmOrg/LiteFarm/blob/2cb33664da0fc61616a32bc4a74cc745c03aadd1/packages/api/db/migration/20200827181040_seed_dev_db.js#L1-L10

**Comment by JimmyRowland** [comment]
migration script:
https://github.com/LiteFarmOrg/LiteFarm/blob/2cb33664da0fc61616a32bc4a74cc745c03aadd1/packages/api/package.json#L20

**Comment by hernandcb** [comment]
Yes, that was it, thank you!

I checked it out and somehow the migration file is not present in the master branch:

![Screenshot from 2021-12-02 11-29-21](https://user-images.githubusercontent.com/4978907/144404810-b6ef331d-1101-4b77-ad85-883015203185.png)

**Comment by hernandcb** [comment]
I just added a follow up issue found in the development branch #1696
