### ISSUE TITLE
Error when adding a new crop variety

### ISSUE THREAD

**Issue by hernandcb** [LiteFarmOrg/LiteFarm#1696]
I tried to add a new variety to a crop (using the development branch) but I received a 400 error.
The error message indicates that the API is expecting an parameter `hs_code_id`:

![Screenshot from 2021-12-02 11-49-44](https://user-images.githubusercontent.com/4978907/144408260-f4b67d34-993f-4e8b-82e2-198747752eac.png)

 but it's not send from the frontend:
![Screenshot from 2021-12-02 11-44-26](https://user-images.githubusercontent.com/4978907/144408325-2f5af73e-26ae-4a05-b76d-acec510d1114.png)

I tried it out in the master branch and it works fine. 
Maybe the hs_code_id makes part of a new feature and the frontend is not ready, or is it something to fix?

Thank you in advance!

H

**Comment by JimmyRowland** [comment]
Fixed

**Comment by JimmyRowland** [comment]
Thanks for raising the issue. I think it's fixed now on develop branch.
